#https://www.memory-lovers.blog/entry/2022/11/18/083000#:~:text=%E8%87%AA%E5%88%86%E3%81%AEPR%E3%81%AF%E8%87%AA%E5%88%86,%E6%89%BF%E8%AA%8D%E3%81%99%E3%82%8B%E3%81%93%E3%81%A8%E3%81%AF%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%9B%E3%82%93%E3%80%82

name: create PR by github-actions[bot]
on:
  push:
    branches-ignore:
      - "master"
    tags:
      - "*"
    workflow_dispatch:

env:
  BASE_BRANCH: master
  REVIEWER: S-Shinzi


jobs:
  create_pr:
    # ブランチが作成されただけならスキップ
    if: ${{ !github.event.created }}
    runs-on: ubuntu-latest
    steps:
      # チェックアウト
      - uses: actions/checkout@v3
        with:
          # PRのタイトルとかをコミット履歴から取得するので、
          # fetch-depthを0に設定して全履歴を取得
          fetch-depth: 0

      # PRがすでに存在していないかのチェック
      # gh pr listでbase/headのブランチが同じPR検索して判定
      - name: check PR
        id: check_pr
        run: |
          echo "count=$(gh pr list -B ${{ env.BASE_BRANCH }} -H ${{ github.ref_name }} --json 'id' -q '.[] | length')" >> $GITHUB_OUTPUT

      # PRがまだなかったらghコマンドで生成
      - name: Create PR
        if: ${{ steps.check_pr.outputs.count == '' }}
        run: gh pr create --fill -B ${{ env.BASE_BRANCH }} -r ${{ env.REVIEWER }}
        env:
          # github-actions[bot]のトークンを使って作成するために設定
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
